In [1]:
import torch

In [2]:
# x = torch.tensor([1])
# x

In [3]:
a = torch.tensor([5.], requires_grad = True)
b = torch.tensor([6.], requires_grad = True)

In [4]:
print(a)

tensor([5.], requires_grad=True)


In [5]:
print(b)

tensor([6.], requires_grad=True)


In [6]:
y = a**3 - b**2

In [8]:
y

tensor([89.], grad_fn=<SubBackward0>)

In [9]:
print(a.grad)

None


In [10]:
print(b.grad)

None


In [11]:
y.backward()

In [12]:
a.grad
# dy/da = 3a**2 = 75 

tensor([75.])

In [13]:
b.grad
#dy/db = -2b = -12

tensor([-12.])

In [34]:
B = torch.randn(10,1, requires_grad = True)
# C = torch.randn(1, requires_grad = True)

In [35]:
print (B)

tensor([[-1.1587],
        [-1.2730],
        [ 0.3565],
        [-0.6052],
        [-2.2560],
        [-0.2498],
        [ 0.2163],
        [-1.3369],
        [ 0.1675],
        [-0.3335]], requires_grad=True)


In [36]:
x = torch.rand(1,10, requires_grad = True)
x

tensor([[0.4579, 0.1775, 0.8125, 0.6393, 0.3102, 0.4309, 0.0282, 0.6939, 0.8724,
         0.0959]], requires_grad=True)

In [37]:
# for linear regression
output = torch.matmul(x,B) + b
output

tensor([[3.5313]], grad_fn=<AddBackward0>)

In [38]:
loss = 1 - output
loss

tensor([[-2.5313]], grad_fn=<RsubBackward1>)

In [39]:
loss.backward()

In [40]:
B.grad

tensor([[-0.4579],
        [-0.1775],
        [-0.8125],
        [-0.6393],
        [-0.3102],
        [-0.4309],
        [-0.0282],
        [-0.6939],
        [-0.8724],
        [-0.0959]])

In [41]:
with torch.no_grad():
    B = B - 0.001 * B.grad.data

In [42]:
B

tensor([[-1.1582],
        [-1.2728],
        [ 0.3573],
        [-0.6045],
        [-2.2557],
        [-0.2493],
        [ 0.2163],
        [-1.3362],
        [ 0.1683],
        [-0.3334]])