In [16]:
import torch
import numpy as np

In [17]:
torch.cuda.is_available()

False

In [18]:
!nvidia-smi

zsh:1: command not found: nvidia-smi


In [19]:
some_data = [[1,2],[3,4]]


In [20]:
some_data

[[1, 2], [3, 4]]

In [21]:
type(some_data)

list

In [22]:
#coverting list of list into tensor
some_data = torch.tensor(some_data)

In [23]:
# np.array(some_data)

In [24]:
some_data

tensor([[1, 2],
        [3, 4]])

In [25]:
numpy_array = np.random.rand(3,4)

In [26]:
numpy_array

array([[0.5282979 , 0.93062419, 0.50792936, 0.39392472],
       [0.58015579, 0.90069821, 0.7269036 , 0.11577991],
       [0.24524528, 0.23628559, 0.673531  , 0.66392994]])

In [27]:
#coverting into tensor

tensor_A = torch.from_numpy(numpy_array)
tensor_A

tensor([[0.5283, 0.9306, 0.5079, 0.3939],
        [0.5802, 0.9007, 0.7269, 0.1158],
        [0.2452, 0.2363, 0.6735, 0.6639]], dtype=torch.float64)

In [30]:
tensor_B = torch.rand(3,4)
tensor_B

tensor([[0.5717, 0.5767, 0.5113, 0.6353],
        [0.3575, 0.7979, 0.5924, 0.1440],
        [0.2789, 0.2395, 0.5724, 0.2735]])

In [31]:
tensor_B.device

device(type='cpu')

In [34]:
tensor_B.dtype

torch.float32

In [35]:
tensor_B.mul(tensor_B)

tensor([[0.3268, 0.3326, 0.2615, 0.4036],
        [0.1278, 0.6367, 0.3509, 0.0207],
        [0.0778, 0.0574, 0.3276, 0.0748]])

In [36]:
tensor_B.matmul(tensor_B.T)

tensor([[1.3244, 1.0589, 0.7640],
        [1.0589, 1.1361, 0.6693],
        [0.7640, 0.6693, 0.5376]])

In [43]:
tensor_C = torch.matmul(tensor_B, tensor_B.T)

In [45]:
# dim-1 is for columns, dim-0 is for rows
torch.nn.functional.softmax(tensor_C, dim = 1)


tensor([[0.4277, 0.3280, 0.2442],
        [0.3626, 0.3917, 0.2456],
        [0.3694, 0.3360, 0.2946]])

In [46]:
tensor_C.shape

torch.Size([3, 3])

In [48]:
tensor_C.size()

torch.Size([3, 3])

In [49]:
# for computer vision problems
tensor_D = torch.rand(10,3,128,128)

In [50]:
tensor_D

tensor([[[[0.8333, 0.7037, 0.0574,  ..., 0.5805, 0.3776, 0.0051],
          [0.5498, 0.9137, 0.8333,  ..., 0.3492, 0.1977, 0.1417],
          [0.9618, 0.8842, 0.6202,  ..., 0.3881, 0.8796, 0.6581],
          ...,
          [0.5232, 0.0139, 0.9092,  ..., 0.0686, 0.5123, 0.7870],
          [0.8830, 0.6362, 0.7725,  ..., 0.6268, 0.8198, 0.3247],
          [0.6595, 0.3979, 0.1892,  ..., 0.0944, 0.0869, 0.2845]],

         [[0.0870, 0.3255, 0.0748,  ..., 0.3172, 0.0460, 0.4137],
          [0.8153, 0.4217, 0.9369,  ..., 0.2963, 0.9958, 0.2451],
          [0.9595, 0.0122, 0.6781,  ..., 0.4408, 0.2939, 0.0654],
          ...,
          [0.0040, 0.0289, 0.2070,  ..., 0.8799, 0.4165, 0.0182],
          [0.6777, 0.0095, 0.3441,  ..., 0.4631, 0.3054, 0.3918],
          [0.3723, 0.9246, 0.6746,  ..., 0.2190, 0.7628, 0.0227]],

         [[0.0581, 0.8921, 0.2448,  ..., 0.2416, 0.2546, 0.1752],
          [0.4166, 0.2324, 0.6415,  ..., 0.0699, 0.4999, 0.3556],
          [0.3117, 0.7207, 0.0028,  ..., 0

In [51]:
tensor_C.clip(0.1,0.9)

tensor([[0.9000, 0.9000, 0.7640],
        [0.9000, 0.9000, 0.6693],
        [0.7640, 0.6693, 0.5376]])

In [52]:
# coverting the tensor into numpy_array
tensor_C.cpu().detach().numpy()

array([[1.3243911 , 1.0589218 , 0.76398444],
       [1.0589218 , 1.1361406 , 0.66927147],
       [0.76398444, 0.66927147, 0.5375716 ]], dtype=float32)